### ISSUE TITLE
Pandoc not found during running bashfile with Path 2) Directly using .Rproj and renv to manage the dependcies

### ISSUE THREAD

**Issue by wenyunie** [wenyunie/speed_dating_analysis#61]
Teammates, Path 1 is running OK. However, it seems the plain computer environment -> .Rproj environment does not work for me.

It seems that pandoc is not installed directly with the system, but with RStudioIDE, so the weird phenomenon is, it is possible to kinit the report from Rstudio, it is impossible for me to directly Rscript "XXX" it from terminal. 
<img width="787" alt="image" src="https://github.com/wenyunie/speed_dating_analysis/assets/143786716/46d82e8f-ec9d-43ee-b9cc-5e012bf472a6">

I tried to install pandoc for my system and this problem is solved, but I'm thinking this is not convenient for people to reproduce our analysis with Path 2) at all.  I am now trying to see if there is a way for us to use renv to manage non-r-package dependencies like this one.

**Comment by wenyunie** [comment]
@wenyunie Exactly, I was not able to find a more elegant automatic solution. Mentioning manual installation of pandoc is necessary. I guess it is because you already have pandoc installed on the system level. Once it is done, you won't meet the problem again. Our base docker image was also too well-round that that it already has pandoc on the system level. That should be why there is only me meeting this on my computer host environment.

**Comment by monazhu** [comment]
Okay yeah that sounds good. Thanks Wenyu!!
