### ISSUE TITLE
clarification of different paths for reproduction in the ReadMe file

### ISSUE THREAD

**Issue by wenyunie** [wenyunie/speed_dating_analysis#63]
Mixed use of renv and dockerization can lead to issues with dependency control:
https://github.com/wenyunie/speed_dating_analysis/issues/60
https://github.com/wenyunie/speed_dating_analysis/issues/59

Using renv to run a .Rproj environment overriding the plain computer environment (Path 2 Reproduction) requires manual installation of system-level dependencies that are not controlled by renv:
https://github.com/wenyunie/speed_dating_analysis/issues/61

readme needs to be updated to clarify these pitfalls.

**Comment by monazhu** [comment]
@wenyunie to confirm, did you want me to update the README or did you want to update the README on your end?
